#-----------------------------------------------#
#                 HungerHealth
#
#                    Cutzuu
#-----------------------------------------------#
# https://github.com/cutzuu/HungerHealth

# Hard Mode sets saturation to zero every time you heal, take damage, or eat.
# Makes the plugin more effective in bringing down health/hunger.
HardMode: true
